### PR TITLE
return videoOwnerChannelTitle instead of channelTitle

### PR DESCRIPTION
**Pull request by thanxx**
this fix addresses the following issue in #184 :
```
 YouTube API - channel name initialized as a channel owner name (i.e. my name) instead of original channel name (where the track belongs to)
 ```

### CODE REVIEW

**Comment by thanxx** [comment]
I hope I didn't break anything for other apis

**Comment by thanxx** [comment]
@natumbri could you please explain what's wrong here?

**Comment by natumbri** [comment]
Oh whoops - nothing wrong; it must have just closed automatically when I merged the branch. Sorry! Where can I see what it does? Is there a front end  that will allow me to see the difference?

**Comment by thanxx** [comment]
@natumbri 
Thanks for the clarification, I was thinking too about auto-closing :)

The fix does the following:

Currently, with YT API the playlist's channel owner is fetching (which is me, because I hold the playlist)
the fix returns the original channel title 

We can also return the original ID to be able to browse through the channels ( I think the slight frontend modification is necessary for that)

So, the current state:
now

And the fix:
1627479258765 fix

**Comment by natumbri** [comment]
What interface are you using on your phone? I currently use the default web client, and I don't think it shows channel owner or title.  I'd be interested in having a look at what is currently being returned by the music API and the webscraping interface.

**Comment by natumbri** [comment]
Have reopened as #196

**Comment by thanxx** [comment]
it's a https://play.google.com/store/apps/details?id=at.co.kemmer.mopidy_mobile

also, in Mopidy-Musicbox-Webclient it's also visible
image

**Pull request closed without merging**
