### PR TITLE
youtube-dl dynamic library switching

### PR DESCRIPTION
**Pull request by Dzordzu**
## Background

In the late youtube-dl had some issues (their code has been taken down due to the DMCA. Now (2021.10.23) it seems to be unmaintained anymore.

## Solution

As history shows there is no "pernament" library. So here it goes - the solution that should be enough for the following time - dynamic library switching

## Changes

- Added `youtube-dl-backend` to the config
- Added dynamic library handling
- Added `yt-dlp` as the dependency

## Related issues and PRs

- Solves: #160

### CODE REVIEW

**Comment by natumbri** [comment]
I had a go: [new branch](/natumbri/mopidy-youtube/tree/fix/dynamic-ytdl-package) 

See what you think?

**Comment by Dzordzu** [comment]
Have you tried to test it? In my case similar approach caused issues with the module mocking in tests

**Comment by Dzordzu** [comment]
Ok it seems to be working. This is much more elegant solution

**Comment by Dzordzu** [comment]
The issue is that youtube_dl seems to be None many times (and set many times)
image

If that's not a problem for you, it's not a problem for me :)

**Comment by Dzordzu** [comment]
Also, I've tested it locally - it works fine

**Comment by Dzordzu** [comment]
I think your branch should be ready to be pushed. Closing this PR for the time

**Comment by natumbri** [comment]
> The issue is that youtube_dl seems to be None many times (and set many times) image
> 
> If that's not a problem for you, it's not a problem for me :)

I think it would be better if this didn't happen, but it doesn't seem to cost much, so I'll just leave as is for now.  Thanks for your input.

**Pull request closed without merging**
