### PR TITLE
performance and usability improvements (ver 3)

### PR DESCRIPTION
**Pull request by chatziko**
Hello,

A new version of #31, trying to improve it. This PR has a single commit, the other commits were changes to address some comments, the intermediate states are not useful. I also simplified the code in various places, added comments, etc.

I understand that the diff is big, I cannot split it in multiple PRs cause all changes are connected.

On the other hand the code is relatively simple. Most changes are in [youtube.py](https://github.com/chatziko/mopidy-youtube/blob/performance-improvements-3/mopidy_youtube/youtube.py) and involve fetching data from youtube (not really mopidy-specific). [backend.py](https://github.com/chatziko/mopidy-youtube/blob/performance-improvements-3/mopidy_youtube/backend.py) is actually much simpler now. So although the diff might look big, going through the whole code can probably be done in less than an hour.

Let me know if I can further simplify things.

Original description: I've been hacking modipy-youtube for a few days now trying to make it _fast_ and improve usability. I ended up implementing several improvements (which, in my experience, make a big overall difference): 
- only handle search, allows browsing with no overhead
- only 2 API calls in search, only takes a couple of secs
- use the Youtube API for metadata, minimizing the number of calls.
  pafy (expensive) is only used for playback
- load data in the background, adding to playing queue is usually instantaneous
- return playlists in search results
- separate all API logic in youtube.py, backend.py is quite clean

Kostas

### CODE REVIEW

**Comment by jcass77** [comment]
I did a quick test and this PR does appear to be much more responsive than the current official release. 

https://github.com/mopidy/mopidy-youtube/issues/21 also isn't a problem here.

**Comment by Chateaudur** [comment]
Hi,
I'm interested in this PR. Is there a way for me to integrate it in my branch if it hasn't been integrated in this development branch?

**Comment by palfrey** [comment]
Ditto. Would you like some help?

**Comment by Chateaudur** [comment]
I'm not sure there is any activity on this project at the time being. I think I'm going to try and use Kostas' fork.

**Comment by kingosticks** [comment]
Perhaps you missed the section in the project readme:

> Mopidy-YouTube is currently kept on life support by the Mopidy core developers. It is in need of a more dedicated maintainer.

**Comment by fopina** [comment]
I was looking into this extension's performance in my RPi1 and decided a PR should be in order to make `ThreadPool` processes configurable.

Using `processes=16` in a single-core raspberry pi 1 where `import pafy` alone takes 3 seconds seemed like a possible issue.

A simple change to use no multiprocessing at all or `processes=2` reduced the time to 1/5!

But nice to see one that possibly improved it even further, I'll be giving it a try for sure

**Comment by fopina** [comment]
I just installed the branch directly in RPi1 and it does nothing.. Not really sure how "loading data in background" is useful for search results and it instantly closes the search query with no results..

**Comment by cmcaine** [comment]
I'm thinking about merging this PR into my local repo and possibly updating this PR.

Does anyone here know if the changes proposed in this PR ever made it into main? If they weren't, does anyone know why?

**Comment by fopina** [comment]
There's no maintainer to merge them...

**Comment by rkkoszewski** [comment]
Seems like the latest commits are from 2017, so somebody seems to have taken over as mantainer. Maybe this PR could be considered to be included? Is it still relevant to improve performance in Mopidy-Youtube? The current Mopidy-Youtube seems pretty slow, but maybe that's how Youtube works.

**Comment by evamvid** [comment]
Is there any update on this? Anybody who can merge the commit?

**Comment by michael-baker** [comment]
Works so much better than the original implementation.
I had to supply my own API key and edit the files in /var/lib/mopidy/.local/lib/python2.7/site-packages/mopidy_youtube to merge the changes in.

Fantastic work.

**Pull request closed without merging**
