### PR TITLE
Overhaul library backend to support cleaner URIs

### PR DESCRIPTION
**Pull request by djmattyg007**
- Video URIs will now be generated in the form 'youtube:video:<id>'
- Playlist URIs will now be generated in the form 'youtube:playlist:<id>'
- URIs of these forms will also be parsed by the extension
- The old styles of URIs should still be supported for the time being
- A better foundation for channels as artists has been laid

This started out as an attempt to address #165 but turned into something a bit bigger, as I felt it made sense in the long term.

There are a couple of miscellaneous fixes in a separate commit, to ensure most tests pass. There is still one test that appears to be failing due to something related to the VCR testing plugin.

### CODE REVIEW

**Comment by natumbri** [comment]
Thanks for this! What I might do is make a new release based on develop and then merge this in, with a view to testing it out and making any consequential changes.

Thanks again for your effort - it does look like a real improvement and I can see the longer term benefits.

**Comment by djmattyg007** [comment]
Sounds like a good idea. I think the most important part of this is ensuring that URIs will now be stable. Previously they would have changed unnecessarily when a video or playlist title changed.

This means bookmarks or other features that use the URI as a primary key will work much better. I actually have some planned additions to the Mopidy Scrobbler extension which will benefit from this, for example.

Also, I'm curious to hear what your thoughts are on a couple of things I noticed:

- what do you want to do about the seemingly random stripping of semicolons in various places?
- what are your thoughts on how channels are/aren't handled right now?

**Comment by djmattyg007** [comment]
I just pushed a new commit that updates the autoplay system to account for the new track URI format.

**Comment by natumbri** [comment]
@djmattyg007 I've just noticed that it sometimes does this:

```
ERROR    2021-04-11 10:14:48,267 [6989:Core-8] mopidy.listener
  Triggering event failed: stream_changed(uri)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/listener.py", line 44, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/actor.py", line 85, in stream_changed
    self.playback._on_stream_changed(uri)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/playback.py", line 147, in _on_stream_changed
    self._trigger_track_playback_started()
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/playback.py", line 514, in _trigger_track_playback_started
    self.core.history._add_track(tl_track.track)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/history.py", line 31, in _add_track
    ", ".join(artist.name for artist in track.artists)
TypeError: sequence item 0: expected str instance, NoneType found
```

The track still plays, but it looks like mopidy doesn't get something that it is expecting (an artist.name).  Happens when adding the tracks referred to in #169 and #172

**Pull request merged**
