### PR TITLE
mopidy-youtube 'reboot' proposal

### PR DESCRIPTION
**Pull request by natumbri**
This pull request proposes to:
- bring the official version of mopidy-youtube into line with the fork I created
- make me the maintainer of the package

I have familiarised myself with the mopidy-youtube code and the current issues with it. I previously submitted a couple of small pull requests against the current code, to close off a couple them. I have closed those pull requests without them being merged.  I have come to the view that, given the state of the official version, there isn't any point incrementally improving it. Instead, I propose a substantial re-write, based on the work of @chatziko and others, and myself.

The current official version of mopidy-youtube is slow and out-of-date. It does not work without a YouTube API key. Most people cannot, or cannot easily, use it. It does not respect mopidy configuration options, such as proxy, and includes new hard-coded settings that should be configuration options.

Based on the limited testing I've done, the version I propose functions at least as well as the current official version:
- It works with Mopidy 3
- It works by default without a YouTube API key
- It includes a number of useful config option  
- It seems fairly performant, and works on very modest hardware

That said, it was hacked together by me, a total amateur. It no doubt has many bugs and, with input from more knowledgeable people, could be substantially improved in terms of efficiency, readability, performance and robustness. 

What do people think?

### CODE REVIEW

**Comment by chatziko** [comment]
Hey, it's been ages since I worked on this but I'm very happy to see someone trying to keep this project alive.

To whoever is making this decision: please merge this!

I'll give it a try when I find some time.

**Comment by fatg3erman** [comment]
Pleased to see someone working on this, it'd be great to have this project brought back to life. I've been using it a couple of days and it's working nicely. Search isn't very accurate but I guess that's a YouTube thing?

**Comment by fatg3erman** [comment]
Been testing it for a while now and I'm seeing some strange inconsistencies with what it reports for the 'Artist' field. One of the changes this PR incorporates is the one I made some time back to use the uploader's display name as the Artist field. Sometimes this is what happens. Other time it using their login name instead. Eg sometimes I'll get 'My Nice Display Name' and other times I'll get 'OxogdhjdhjssbYH', for videos by the same user. There doesn't seem to be any pattern to it. I've been provoking it by doing a lot of searches.

**Comment by natumbri** [comment]
@fatg3erman Thanks for the feedback; I'd be interested to see the inconsistencies you've mentioned.  
Are you using it with an API key or without (or both)?  
Are you able to give some examples so I can replicate and investigate?  

It would be useful to have the search terms and the videoIds.  If it is happening only when running without the API key, it is possibly to do with the regex, which I haven't tested that carefully...

Feel free to open an issue (on my fork), with the details.

Thanks again for testing it out and for providing feedback!

Cheers,
Nik

**Comment by fatg3erman** [comment]
@natumbri With an API Key??? I thought this branch didn't need an API key? have I misundersood something?

**Pull request merged**
