### PR TITLE
Add YouTube Music search provider

### PR DESCRIPTION
**Pull request by DonnieWest**
Not sure if this is desired, but I added a sort of rudimentary YouTube Music based search provider. I took a lot of inspiration from the jAPI implementation, which is similar but not music specific

I still need to:

* Implement pagination (we only get first page results as of right now)
* Reduce some hard coded values and/or make them configurable (not everyone is in the US)
* Call out how utterly experimental this is and how likely it is that YouTube Music breaks this implementation
* Implement any feedback given
* Remove constraint to search only by "Any", since the YouTube Music API allows us to search by Artist, Album or Song
* Add tests and fix failing tests

If this isn't wanted, feel free to tell me and I'll just maintain this little class for my own fork or spin this off into `mopidy-youtube-music` :)

### CODE REVIEW

**Comment by natumbri** [comment]
Thanks for this - it looks very interesting! I'll have a proper look when I get a chance and will have a think about how it might fit in.

**Comment by DonnieWest** [comment]
Just removed a hardcoded search query, and added in pagination support. It currently exhausts ALL the pages though, so beware of your YouTube API key limits. I've used up all my access on accident :joy:

**Comment by natumbri** [comment]
Is there documentation for the YouTube Music API?

**Comment by DonnieWest** [comment]
Unfortunately not, it's not technically a public API and it's something I reverse engineered off of the YouTube Music app

**Comment by natumbri** [comment]
Oh, I see. Interesting. I couldn't exactly work out what you're doing to get the API key. Can you explain how that works?

**Comment by DonnieWest** [comment]
It's querying the YouTube music home page. Injected into the html via a script tag is a JSON object that contains an API key. We grab that json with regex, parse it, and grab the key from it. After that, we memoize it

**Comment by natumbri** [comment]
I merged this into a new branch for further development - [feature/youtubeMusic](/natumbri/mopidy-youtube/tree/feature/youtubeMusic)

**Pull request closed without merging**
